export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const VERIFY_USER = 'VERIFY_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const LOGOUT = 'LOGOUT'; 
export const SET_AUTH_USER_DATA = 'SET_AUTH_USER_DATA';
export const SET_IS_AUTH = 'SET_IS_AUTH';
export const SET_IS_START_DATA = 'SET_IS_START_DATA';

export const SET_EXERCISES_DATA = 'SET_EXERCISES_DATA'; 
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const UPDATE_EXERCISES = 'UPDATE_EXERCISES';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const GET_EXERCISES = 'GET_EXERCISES';

export const SET_WORKOUTS_DATA = 'SET_WORKOUTS_DATA';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SET_SELECTED_WORKOUT_ID = 'SET_SELECTED_WORKOUT_ID';
export const SET_IS_HAVE_WORKOUT = 'SET_IS_HAVE_WORKOUT';
export const ADD_WORKOUT = 'ADD_WORKOUT';
export const UPDATE_WORKOUT = 'UPDATE_WORKOUT';
export const GET_WORKOUTS = 'GET_WORKOUTS';


export const SET_IS_SHOW_MODAL = 'SET_IS_SHOW_MODAL';
export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const SET_SERVER_MESSAGE = 'SET_SERVER_MESSAGE';
export const SET_IS_REDIRECT_AFTER_SUBMIT = 'SET_IS_REDIRECT_AFTER_SUBMIT';
export const SET_IS_FORM_SUCCESS = 'SET_IS_FORM_SUCCESS';